In [1]:
#嵌入显示：让图形直接显示在单元格下方。Jupyter 环境专用
%matplotlib inline


PyTorch是什么?

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始

Tensors（张量）

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [2]:
from __future__ import print_function
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建一个随机初始化的矩阵:



In [4]:
# torch.rand	均匀分布 (Uniform)	[0, 1)   权重初始化、随机选择
x = torch.rand(5, 3)
print(x)

tensor([[0.8746, 0.6098, 0.2790],
        [0.7151, 0.4327, 0.2644],
        [0.5545, 0.5627, 0.3072],
        [0.5455, 0.6501, 0.7274],
        [0.9461, 0.8059, 0.8911]])


In [8]:
#torch.randn	标准正态分布 (Standard Normal)	(-∞, +∞)  深度学习初始化、噪声添加
x = torch.randn(5, 3)
print(x)

tensor([[-2.3335, -0.8205,  1.2638],
        [ 1.1137, -1.0677,  0.7331],
        [-1.6212, -1.6803,  1.1686],
        [-0.6884, -1.1079, -1.0964],
        [-0.9691, -0.1758, -0.0834]])


创建一个0填充的矩阵，数据类型为long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0571, -2.1044, -0.2607],
        [ 0.6188, -0.5309,  0.3718],
        [-0.3354, -1.1547, -0.6839],
        [-0.0206,  1.7976, -0.0591],
        [-1.0932, -0.5831,  1.2824]])


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [12]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple 元祖类型, 所以它支持tuple类型的所有操作.</p></div>

操作

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [9]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-2.3335, -0.8205,  1.2638],
        [ 1.1137, -1.0677,  0.7331],
        [-1.6212, -1.6803,  1.1686],
        [-0.6884, -1.1079, -1.0964],
        [-0.9691, -0.1758, -0.0834]])
tensor([[0.9004, 0.4146, 0.7561],
        [0.3356, 0.0900, 0.2979],
        [0.7681, 0.3770, 0.0885],
        [0.2236, 0.4647, 0.4549],
        [0.5797, 0.7604, 0.8063]])
tensor([[-1.4331, -0.4059,  2.0199],
        [ 1.4493, -0.9777,  1.0310],
        [-0.8531, -1.3032,  1.2570],
        [-0.4648, -0.6431, -0.6415],
        [-0.3895,  0.5846,  0.7229]])


加法2


In [10]:
print(torch.add(x, y))

tensor([[-1.4331, -0.4059,  2.0199],
        [ 1.4493, -0.9777,  1.0310],
        [-0.8531, -1.3032,  1.2570],
        [-0.4648, -0.6431, -0.6415],
        [-0.3895,  0.5846,  0.7229]])


提供输出tensor作为参数



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.4331, -0.4059,  2.0199],
        [ 1.4493, -0.9777,  1.0310],
        [-0.8531, -1.3032,  1.2570],
        [-0.4648, -0.6431, -0.6415],
        [-0.3895,  0.5846,  0.7229]])


替换



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.4331, -0.4059,  2.0199],
        [ 1.4493, -0.9777,  1.0310],
        [-0.8531, -1.3032,  1.2570],
        [-0.4648, -0.6431, -0.6415],
        [-0.3895,  0.5846,  0.7229]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [14]:
print(x)
#x[:, 1] 表示：取所有行的第1列（注意：索引从0开始）
# `:` 表示"所有行"
print(x[:, 1])

tensor([[-2.3335, -0.8205,  1.2638],
        [ 1.1137, -1.0677,  0.7331],
        [-1.6212, -1.6803,  1.1686],
        [-0.6884, -1.1079, -1.0964],
        [-0.9691, -0.1758, -0.0834]])
tensor([-0.8205, -1.0677, -1.6803, -1.1079, -0.1758])


``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3367])
-1.3366940021514893


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [21]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改

In [23]:
if torch.cuda.is_available():
    device = torch.device('cuda')
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    device = torch.device('mps')  # Apple Silicon (M1/M2/M3)
else:
    device = torch.device('cpu')
y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
x = x.to(device)                       # 或者直接使用``.to("mps")``将张量移动到mps中
z = x + y
print(z)
#mps不能使用torch.double
#MPS 只支持 float16 和 float32，不支持 float64
#TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
print(z.to("cpu", torch.float32))       # ``.to`` 也会对变量的类型做更改

tensor([-0.3367], device='mps:0')
tensor([-0.3367])
